from __future__ import print_function

import mysql.connector
from mysql.connector import errorcode

DB_NAME = 'Stage_database'

TABLES = {}
TABLES['Stage_Profiles'] = """CREATE TABLE Stage_Profiles (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
mpg_array varchar(50),
source varchar(50) not null,
update_ts varchar(50),
user_id varchar(50) not null,
constraint con unique (user_id, source))"""

TABLES['Stage_pipeline_state'] = """CREATE TABLE Stage_pipeline_state (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
curr_run_ts varchar(100),
last_processed_ts decimal(5,5),
last_ts_run decimal(5,5),
pipeline_stage mediumint,
user_id varchar(50) not null,
constraint uniques unique (user_id))"""

TABLES['Stage_usercache'] = """CREATE TABLE Stage_usercache (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
update_ts varchar(50),
user_email varchar(250),
uuid varchar(50) not null)"""

TABLES['Stage_uuids'] = """CREATE TABLE Stage_uuids (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
update_ts varchar(50),
user_email varchar(250) not null,
uuid varchar(50) not null,
constraint uniques unique (user_email,uuid))"""

TABLES['timeseries_location'] = """CREATE TABLE Timeseries_location (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_accuracy mediumint,
data_altitude decimal(5,5),
data_filter varchar(100),
data_fmt_time varchar(250),
data_heading decimal(5,5),
data_latitude decimal(5,5),
data_loc_coordinates varchar(200),
data_loc_type varchar(100),
data_local_dt_day bigint,
data_local_dt_hour bigint,
data_local_dt_minute bigint,
data_local_dt_month bigint,
data_local_dt_second bigint,
data_local_dt_timezone varchar(100),
data_local_dt_weekday bigint,
data_local_dt_year bigint,
data_longitude decimal(5,5),
data_sensed_speed decimal(5,5),
data_ts decimal(5,5),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['timeseries_motionactivity'] = """CREATE TABLE Timeseries_motionactivity (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_confidence decimal(5,5),
data_fmt_time varchar(250),
data_local_dt_day bigint,
data_local_dt_hour bigint,
data_local_dt_minute bigint,
data_local_dt_month bigint,
data_local_dt_second bigint,
data_local_dt_timezone varchar(100),
data_local_dt_weekday bigint,
data_local_dt_year bigint,
data_type bigint,
data_ts decimal(5,5),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['timeseries_transition'] = """CREATE TABLE Timeseries_transition (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_curr_state bigint,
data_fmt_time varchar(250),
data_local_dt_day bigint,
data_local_dt_hour bigint,
data_local_dt_minute bigint,
data_local_dt_month bigint,
data_local_dt_second bigint,
data_local_dt_timezone varchar(100),
data_local_dt_weekday bigint,
data_local_dt_year bigint,
data_transition bigint,
data_ts decimal(5,5),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['timeseries_statsevent'] = """CREATE TABLE Timeseries_statsevent (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_name varchar(250),
data_reading decimal(5,5),
data_ts decimal(5,5),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['analysis_timeseries_trip'] = """CREATE TABLE Analysis_timeseries_trip (
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_distance decimal(5,5),
data_duration decimal(5,5),
data_end_fmt_time varchar(250),
data_end_loc_coordinates varchar(200),
data_end_loc_type varchar(100),
data_end_local_dt_day bigint,
data_end_local_dt_hour bigint,
data_end_local_dt_minute bigint,
data_end_local_dt_month bigint,
data_end_local_dt_second bigint,
data_end_local_dt_timezone varchar(100),
data_end_local_dt_weekday bigint,
data_end_local_dt_year bigint,
data_end_place varchar(50),
data_end_ts decimal(5,5),
data_raw_trip varchar(50),
data_source varchar(100),
data_start_fmt_time varchar(250),
data_start_loc_coordinates varchar(200),
data_start_loc_type varchar(100),
data_start_local_dt_day bigint,
data_start_local_dt_hour bigint,
data_start_local_dt_minute bigint,
data_start_local_dt_month bigint,
data_start_local_dt_second bigint,
data_start_local_dt_timezone varchar(100),
data_start_local_dt_weekday bigint,
data_start_local_dt_year bigint,
data_start_place varchar(50),
  
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['analysis_timeseries_section'] = """CREATE TABLE Analysis_timeseries_section (
_id varchar(50),
data_distance decimal(5,5),
data_distances varchar(250),
data_duration decimal(5,5),
data_end_fmt_time varchar(250),
data_end_loc_coordinates varchar(200),
data_end_loc_type varchar(100),
data_end_local_dt_day bigint,
data_end_local_dt_hour bigint,
data_end_local_dt_minute bigint,
data_end_local_dt_month bigint,
data_end_local_dt_second bigint,
data_end_local_dt_timezone varchar(100),
data_end_local_dt_weekday bigint,
data_end_local_dt_year bigint,
data_end_stop varchar(50),
data_end_ts decimal(5,5),
data_sensed_mode mediumint,
data_source varchar(100),
data_speeds varchar(250),
data_start_fmt_time varchar(250),
data_start_loc_coordinates varchar(200),
data_start_loc_type varchar(100),
data_start_local_dt_day bigint,
data_start_local_dt_hour bigint,
data_start_local_dt_minute bigint,
data_start_local_dt_month bigint,
data_start_local_dt_second bigint,
data_start_local_dt_timezone varchar(100),
data_start_local_dt_weekday bigint,
data_start_local_dt_year bigint,
data_start_ts decimal(5,5),
data_trip_id varchar(50),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""

TABLES['analysis_timeseries_stop'] = """CREATE TABLE Analysis_timeseries_stop (
_id varchar(50),
data_distance decimal(5,5),
data_duration decimal(5,5),
data_ending_section varchar(50),
data_enter_fmt_time varchar(250),
data_enter_loc_coordinates varchar(200),
data_enter_loc_type varchar(100),
data_enter_local_dt_day bigint,
data_enter_local_dt_hour bigint,
data_enter_local_dt_minute bigint,
data_enter_local_dt_month bigint,
data_enter_local_dt_second bigint,
data_enter_local_dt_timezone varchar(100),
data_enter_local_dt_weekday bigint,
data_enter_local_dt_year bigint,
data_enter_stop varchar(50),
data_enter_ts decimal(5,5),
data_exit_fmt_time varchar(250),
data_exit_loc_coordinates varchar(200),
data_exit_loc_type varchar(100),
data_exit_local_dt_day bigint,
data_exit_local_dt_hour bigint,
data_exit_local_dt_minute bigint,
data_exit_local_dt_month bigint,
data_exit_local_dt_second bigint,
data_exit_local_dt_timezone varchar(100),
data_exit_local_dt_weekday bigint,
data_exit_local_dt_year bigint,
data_exit_place varchar(50),
data_source varchar(100),
data_starting_section varchar(50),
  
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""


TABLES['analysis_timeseries_place'] = """CREATE TABLE Analysis_timeseries_place(
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_exit_fmt_time varchar(250),
data_exit_local_dt_day bigint,
data_exit_local_dt_hour bigint,
data_exit_local_dt_minute bigint,
data_exit_local_dt_month bigint,
data_exit_local_dt_second bigint,
data_exit_local_dt_timezone varchar(100),
data_exit_local_dt_weekday bigint,
data_exit_local_dt_year bigint,
data_exit_ts decimal(5,5),
data_exit_location_coordinates varchar(200),
data_exit_location_type varchar(100),
data_raw_place varchar(50),
data_source varchar(100),
data_starting_trip varchar(250),
  
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""


TABLES['analysis_timeseries_smoothedresults'] = """CREATE TABLE Analysis_timeseries_smoothedresults(
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_deleted_points varchar(250),
data_filtering_algo varchar(250),
data_outlier_algo varchar(250),
data_section varchar(50),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""


TABLES['inference_timeseries_prediction'] = """CREATE TABLE Inference_timeseries_prediction(
row_id mediumint not null auto_increment,
primary key (row_id),
_id varchar(50),
data_algorithm_id mediumint,
data_end_ts decimal(5,5),
data_mode_map varchar(250),
data_section_id varchar(50),
data_start_ts decimal(5,5),
data_trip_id varchar(250),
metadata_key varchar(100),
metadata_platform varchar(100),
metadata_read_ts decimal(5,5),
metadata_time_zone varchar(100),
metadata_type varchar(100),
metadata_write_fmt_time varchar(100),
metadata_write_local_dt_day bigint,
metadata_write_local_dt_hour bigint,
metadata_write_local_dt_minute bigint,
metadata_write_local_dt_month bigint,
metadata_write_local_dt_second bigint,
metadata_write_local_dt_timezone varchar(100),
metadata_write_local_dt_weekday bigint,
metadata_write_local_dt_year bigint,
metadata_write_ts decimal(5,5),
user_id varchar(50) not null)"""